# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Redes 2
author: Departamento ATC
logo: logo.png

execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/joselsegura/redes2-lab
  branch: main

html:
  use_issues_button: true
  use_repository_button: true


parse:
  myst_enable_extensions:
    - deflist
